title: "Vlad Lidiaev"
theme: null
remote_theme: just-the-docs/just-the-docs

url: "https://lidiaev.github.io"
baseurl: ""

permalink: pretty

search_enabled: true

toc_enabled: true
toc_min_heading_level: 2
toc_max_heading_level: 4

aux_links:
  "GitHub":
    - "https://github.com/lidiaev"

